version = 0.1

[default.deploy.parameters]
stack_name = "checkIdleEc2"
resolve_s3 = true
s3_prefix = "checkIdleEc2"
region = "us-east-1"
profile = "dev"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
