AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Check Idle resources in EC2 using AWS SAM

Globals:
  Function:
    Runtime: python3.11       # no patch version
    Timeout: 30
    MemorySize: 128
    CodeUri: .                # default code location inside this folder

Resources:
  CheckIdleEC2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.check_idle_ec2   # your handler function in app.py
      Policies:
        - CloudWatchReadOnlyAccess
        - AWSLambdaBasicExecutionRole
        - AmazonEC2ReadOnlyAccess
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)  # Runs once an hour
