AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cleanup old S3 buckets using AWS SAM

Global:
  FunctionRuntime: python3.11.2
  CodeUri: ./lambdas/s3_cleanup/
  Timeout: 30
  MemorySize: 128

Resources:
  S3CleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.s3_cleanup
      Runtime: python3.11.2
      CodeUri: ./lambdas/s3_cleanup/
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        VPC_ID: !Ref VPCID
        SUBNET_IDS: !Ref SubnetIDs
        SECURITY_GROUP_IDS: !Ref SecurityGroupIDs
